"""Smoke tests against a real Oracle (testcontainers or $ORACDB_TEST_DSN).

Every test is marked ``@pytest.mark.integration``. Unit-only runs
(``pytest -q``) skip the whole directory by default; opt in with
``pytest -m integration``.

These are the contracts the mock-based unit suite can't prove:
1. ``CREATE TABLE oracdb$jobs`` and ``oracdb$tables`` actually work,
   and ``ensure_schema`` is genuinely idempotent.
2. ``AS OF SCN :scn`` reads return a consistent snapshot under
   concurrent writes.
3. ``ALTER SEQUENCE … RESTART`` works against 23c-free.
4. End-to-end ``oracdb plan`` → ``run`` → ``status`` → ``verify``.
5. FK disable/enable cycle is respected.
"""
from __future__ import annotations

import pytest

pytestmark = pytest.mark.integration


# ---------------------------------------------------------------------------
# 1. Connectivity
# ---------------------------------------------------------------------------


def test_connection_works(oracle_conn: object) -> None:
    """Sanity: we can SELECT 1 against the container."""
    cur = oracle_conn.cursor()  # type: ignore[attr-defined]
    cur.execute("SELECT 1 FROM dual")
    assert cur.fetchone() == (1,)


def test_endpoint_connect_via_endpoint(oracle_endpoint: object) -> None:
    conn = oracle_endpoint.connect()  # type: ignore[attr-defined]
    try:
        cur = conn.cursor()
        cur.execute("SELECT user FROM dual")
        row = cur.fetchone()
        assert row[0]
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# 2. state schema
# ---------------------------------------------------------------------------


def test_ensure_schema_creates_tables_and_is_idempotent(
    oracle_conn: object,
) -> None:
    from oracle_schema_refresh.state import schema as state_schema

    state_schema.ensure_schema(oracle_conn)  # type: ignore[arg-type]
    state_schema.ensure_schema(oracle_conn)  # idempotent

    cur = oracle_conn.cursor()  # type: ignore[attr-defined]
    cur.execute(
        "SELECT table_name FROM user_tables WHERE table_name IN "
        "('ORACDB$JOBS','ORACDB$TABLES')"
    )
    names = {row[0] for row in cur.fetchall()}
    assert names == {"ORACDB$JOBS", "ORACDB$TABLES"}

    # Clean up
    cur.execute("DROP TABLE oracdb$tables CASCADE CONSTRAINTS PURGE")
    cur.execute("DROP TABLE oracdb$jobs CASCADE CONSTRAINTS PURGE")
    oracle_conn.commit()  # type: ignore[attr-defined]


# ---------------------------------------------------------------------------
# 3. end-to-end same-instance refresh against fresh schemas
# ---------------------------------------------------------------------------


def _populate_source(
    oracle_conn: object, src_schema: str, n_rows: int = 50
) -> None:
    cur = oracle_conn.cursor()  # type: ignore[attr-defined]
    cur.execute(
        f'CREATE TABLE "{src_schema}"."PEOPLE" ('
        f"  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        f"  name VARCHAR2(100),"
        f"  age NUMBER"
        f")"
    )
    cur.executemany(
        f'INSERT INTO "{src_schema}"."PEOPLE" (name, age) VALUES (:1, :2)',
        [(f"person_{i}", 20 + i % 60) for i in range(n_rows)],
    )
    oracle_conn.commit()  # type: ignore[attr-defined]


def test_same_instance_refresh_end_to_end(
    oracle_conn: object, fresh_schemas: tuple[str, str], oracle_dsn: tuple[str, str, str]
) -> None:
    """schema-refresh path (legacy CLI's engine) copies PEOPLE → target."""
    from pydantic import SecretStr

    from oracle_schema_refresh.config import RefreshConfig
    from oracle_schema_refresh.endpoints import Endpoint
    from oracle_schema_refresh.engine import RefreshEngine

    src, tgt = fresh_schemas
    _populate_source(oracle_conn, src, n_rows=25)

    user, password, dsn = oracle_dsn
    ep = Endpoint(name="x", dsn=dsn, username=user, password=SecretStr(password))
    cfg = RefreshConfig(
        source_schema=src,
        target_schema=tgt,
        tables=["PEOPLE"],
        auto_include_fk_parents=False,
    )
    engine = RefreshEngine(ep, cfg)
    result = engine.run(dry_run=False)

    assert result.success is True
    r = result.table_results[0]
    assert r.status == "ok"
    assert r.rows_source == 25
    assert r.rows_loaded == 25
    assert r.match is True
    # Identity sequence on the new IDENTITY column should have been reset.
    assert r.sequences_reset, "expected the identity-backed sequence to reset"


# ---------------------------------------------------------------------------
# 4. AS OF SCN consistent read under concurrent writes
# ---------------------------------------------------------------------------


def test_as_of_scn_sees_snapshot_under_concurrent_insert(
    oracle_conn: object, fresh_schemas: tuple[str, str], oracle_dsn: tuple[str, str, str]
) -> None:
    """Capture SCN, INSERT a new row, then read AS OF SCN — must NOT see
    the new row. Proves Flashback Query is doing what we rely on."""
    import oracledb

    src, _tgt = fresh_schemas
    cur = oracle_conn.cursor()  # type: ignore[attr-defined]
    cur.execute(
        f'CREATE TABLE "{src}"."T" (id NUMBER PRIMARY KEY, v VARCHAR2(20))'
    )
    cur.executemany(
        f'INSERT INTO "{src}"."T" VALUES (:1, :2)',
        [(i, f"v{i}") for i in range(10)],
    )
    oracle_conn.commit()  # type: ignore[attr-defined]

    cur.execute("SELECT current_scn FROM v$database")
    scn = int(cur.fetchone()[0])

    # Race: insert a new row AFTER the snapshot.
    user, password, dsn = oracle_dsn
    second = oracledb.connect(user=user, password=password, dsn=dsn)
    try:
        c2 = second.cursor()
        c2.execute(f'INSERT INTO "{src}"."T" VALUES (999, :v)', v="post-scn")
        second.commit()
    finally:
        second.close()

    cur.execute(f'SELECT COUNT(*) FROM "{src}"."T" AS OF SCN :scn', scn=scn)
    snapshot_count = int(cur.fetchone()[0])
    cur.execute(f'SELECT COUNT(*) FROM "{src}"."T"')
    current_count = int(cur.fetchone()[0])

    assert snapshot_count == 10
    assert current_count == 11


# ---------------------------------------------------------------------------
# 5. ALTER SEQUENCE RESTART on 23c
# ---------------------------------------------------------------------------


def test_alter_sequence_restart_works_on_23c(oracle_conn: object) -> None:
    cur = oracle_conn.cursor()  # type: ignore[attr-defined]
    cur.execute("CREATE SEQUENCE oracdb_test_seq START WITH 1 INCREMENT BY 1")
    try:
        cur.execute("SELECT oracdb_test_seq.NEXTVAL FROM dual")
        cur.execute("SELECT oracdb_test_seq.NEXTVAL FROM dual")
        cur.execute("ALTER SEQUENCE oracdb_test_seq RESTART START WITH 100")
        cur.execute("SELECT oracdb_test_seq.NEXTVAL FROM dual")
        assert cur.fetchone()[0] == 100
    finally:
        cur.execute("DROP SEQUENCE oracdb_test_seq")


# ---------------------------------------------------------------------------
# 6. oracdb plan → run → status → verify end-to-end
# ---------------------------------------------------------------------------


def test_oracdb_pipeline_end_to_end(
    oracle_conn: object,
    fresh_schemas: tuple[str, str],
    oracle_dsn: tuple[str, str, str],
    tmp_path,  # pytest builtin
) -> None:
    """Exercise the full plan / run / status / verify flow via the
    Click CLI runner so we're going through the public interface."""
    import json
    import os

    from click.testing import CliRunner

    from oracle_schema_refresh.oracdb_cli import oracdb

    src, tgt = fresh_schemas
    _populate_source(oracle_conn, src, n_rows=10)

    user, password, dsn = oracle_dsn

    # Isolate the registry + ORACDB_HOME under tmp_path.
    env = {
        **os.environ,
        "ORACDB_REGISTRY": str(tmp_path / "endpoints.yaml"),
        "ORACDB_HOME": str(tmp_path / ".oracdb"),
    }
    runner = CliRunner()

    # register the same endpoint as source and target — same instance.
    r = runner.invoke(
        oracdb,
        ["endpoints", "add", "test",
         "--dsn", dsn, "--user", user, "--password", password],
        env=env,
    )
    assert r.exit_code == 0, r.output

    # plan
    r = runner.invoke(
        oracdb,
        [
            "plan",
            "--from", "test", "--to", "test",
            "--source-schema", src, "--target-schema", tgt,
            "--tables", "PEOPLE",
            "--no-auto-fk",
            "--json",
        ],
        env=env,
    )
    assert r.exit_code == 0, r.output
    plan_env = json.loads(r.output)
    job_id = plan_env["job_id"]
    assert plan_env["data"]["table_order"] == ["PEOPLE"]

    # run (foreground)
    r = runner.invoke(oracdb, ["run", job_id, "--json"], env=env)
    assert r.exit_code == 0, r.output

    # status
    r = runner.invoke(oracdb, ["status", job_id, "--json"], env=env)
    assert r.exit_code == 0, r.output
    status_env = json.loads(r.output)
    assert status_env["data"]["status"] == "DONE"

    # verify
    r = runner.invoke(oracdb, ["verify", job_id, "--json"], env=env)
    assert r.exit_code == 0, r.output
    verify_env = json.loads(r.output)
    assert verify_env["data"]["all_match"] is True


# ---------------------------------------------------------------------------
# 7. FK disable/enable cycle
# ---------------------------------------------------------------------------


def test_fk_disable_enable_cycle_around_load(
    oracle_conn: object,
    fresh_schemas: tuple[str, str],
    oracle_dsn: tuple[str, str, str],
) -> None:
    from pydantic import SecretStr

    from oracle_schema_refresh.config import RefreshConfig
    from oracle_schema_refresh.endpoints import Endpoint
    from oracle_schema_refresh.engine import RefreshEngine

    src, tgt = fresh_schemas
    cur = oracle_conn.cursor()  # type: ignore[attr-defined]

    # Source: parent + child with FK.
    cur.execute(
        f'CREATE TABLE "{src}"."PARENT" (id NUMBER PRIMARY KEY, label VARCHAR2(20))'
    )
    cur.execute(
        f'CREATE TABLE "{src}"."CHILD" ('
        f"  id NUMBER PRIMARY KEY,"
        f"  parent_id NUMBER NOT NULL,"
        f'  CONSTRAINT child_fk FOREIGN KEY (parent_id) REFERENCES "{src}"."PARENT"(id)'
        f")"
    )
    cur.executemany(
        f'INSERT INTO "{src}"."PARENT" VALUES (:1, :2)',
        [(i, f"p{i}") for i in range(5)],
    )
    cur.executemany(
        f'INSERT INTO "{src}"."CHILD" VALUES (:1, :2)',
        [(i, i % 5) for i in range(15)],
    )
    oracle_conn.commit()  # type: ignore[attr-defined]

    user, password, dsn = oracle_dsn
    ep = Endpoint(name="x", dsn=dsn, username=user, password=SecretStr(password))
    cfg = RefreshConfig(
        source_schema=src,
        target_schema=tgt,
        tables=["CHILD"],  # FK parent discovery should pull in PARENT
        auto_include_fk_parents=True,
    )
    result = RefreshEngine(ep, cfg).run(dry_run=False)

    assert result.success is True
    statuses = {r.table_name: r.status for r in result.table_results}
    assert statuses == {"PARENT": "ok", "CHILD": "ok"}
    # Topological order: parent before child.
    assert result.table_order == ["PARENT", "CHILD"]
